spring:
  profiles:
    active: dev
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://dpg-cnuspool5elc73atc9d0-a.singapore-postgres.render.com:5432/olta
    username: fund_manager
    password: yN9QC5VxQoxVVHZ9HLwa0MQGrjyuq0P0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

